"""CSV register for invoices generated by the Streamlit app."""
from __future__ import annotations

import csv
import fcntl
import io
import os
import tempfile
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

from invoice_generator import Ticket, Totals


REGISTER_PATH = Path(__file__).resolve().parent / "generated_invoices.csv"
LEGACY_FIELDS = (
    "invoice_number", "generated_at_utc", "issued_date", "travel_date",
    "passenger_name", "destination", "tbo_pnr", "riya_pnr",
    "customer_name", "customer_gstin", "seller_name", "net",
    "seat_amount", "ticket_cost", "processing_charges", "gst_rate",
    "gst", "net_invoice_amount", "remark",
)
FIELDS = (*LEGACY_FIELDS, "revision")


@contextmanager
def _register_lock(path: Path):
    # A separate lock stays valid when atomic replacement changes the CSV inode.
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.with_suffix(path.suffix + ".lock").open("a") as handle:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)


def _read_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            return []
        if reader.fieldnames not in (list(FIELDS), list(LEGACY_FIELDS)):
            raise ValueError("Invoice CSV columns do not match the current register format.")
        return [{**row, "revision": row.get("revision", "1")} for row in reader]


def _row(ticket: Ticket, totals: Totals, number: str, seller_name: str) -> dict[str, str]:
    return {
        "invoice_number": number,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "issued_date": ticket.issued_date.isoformat(),
        "travel_date": ticket.travel_date.isoformat(),
        "passenger_name": ticket.passenger_name,
        "destination": ticket.destination,
        "tbo_pnr": ticket.tbo_pnr,
        "riya_pnr": ticket.riya_pnr,
        "customer_name": ticket.company_name,
        "customer_gstin": ticket.company_gstin,
        "seller_name": seller_name,
        "net": f"{totals.net:.2f}",
        "seat_amount": f"{totals.seat_amount:.2f}",
        "ticket_cost": f"{totals.ticket_cost:.2f}",
        "processing_charges": f"{totals.processing_charges:.2f}",
        "gst_rate": f"{totals.gst_rate:.3f}",
        "gst": f"{totals.gst:.2f}",
        "net_invoice_amount": f"{totals.net_amount:.2f}",
        "remark": ticket.remark,
    }


def append_invoice(ticket: Ticket, totals: Totals, number: str, seller_name: str,
                   path: Path | None = None, *, revision: int = 1) -> None:
    """Save a revision atomically, migrating legacy rows on the first write."""
    path = path or REGISTER_PATH
    if type(revision) is not int or revision < 1:
        raise ValueError("Revision must be a positive integer.")
    row = {**_row(ticket, totals, number, seller_name), "revision": str(revision)}
    with _register_lock(path):
        rows = _read_rows(path)
        previous = [r for r in rows if r["invoice_number"] == number]
        for existing in previous:
            if existing["revision"] == str(revision):
                if all(existing[k] == row[k] for k in FIELDS if k != "generated_at_utc"):
                    return  # Retrying an accepted revision never duplicates it.
                raise ValueError("This invoice revision already exists with different values.")
        latest = max((int(r["revision"]) for r in previous), default=0)
        if revision != latest + 1:
            raise ValueError("Invoice revision is out of date. Reload the invoice before editing.")
        rows.append(row)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="",
                                             dir=path.parent, delete=False) as handle:
                temporary = Path(handle.name)
                writer = csv.DictWriter(handle, fieldnames=FIELDS)
                writer.writeheader()
                writer.writerows(rows)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, path)
        finally:
            if temporary is not None:
                temporary.unlink(missing_ok=True)


def read_invoices(path: Path | None = None) -> list[dict[str, str]]:
    path = path or REGISTER_PATH
    if not path.exists():
        return []
    with _register_lock(path):
        return _read_rows(path)


def latest_invoices(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    latest = {}
    for row in rows:
        number = row["invoice_number"]
        if number not in latest or int(row["revision"]) > int(latest[number]["revision"]):
            latest[number] = row
    return list(latest.values())


def export_csv(rows: list[dict[str, str]]) -> bytes:
    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=FIELDS)
    writer.writeheader()
    writer.writerows(rows)
    return output.getvalue().encode("utf-8-sig")
