"""View and export the generated invoice register."""
import streamlit as st

from invoice_register import export_csv, latest_invoices, read_invoices


st.title("Generated invoices")
st.caption("Invoices generated by this app are listed here. Download the CSV to keep a copy.")

try:
    rows = read_invoices()
except (OSError, ValueError) as exc:
    st.error(f"Could not read the invoice CSV: {exc}")
else:
    if not st.checkbox("Show all revisions"):
        rows = latest_invoices(rows)
    if rows:
        st.dataframe(list(reversed(rows)), hide_index=True, width="stretch")
    else:
        st.info("No invoices have been generated yet.")
    st.download_button(
        "Download CSV",
        data=export_csv(rows),
        file_name="generated_invoices.csv",
        mime="text/csv",
        on_click="ignore",
    )
